language: rust
dist: "trusty"
before_install:
  - pyenv install 3.6.3
  - pyenv global 3.6.3

install:
  - pip3 install virtualenv
  - make venv
  - make setup

script:
  - bash tools/check_esp32.sh
  - bash tools/check_stm32.sh