[package]
name = "svdtools"
version = "0.1.0"
authors = ["MarcoIeni"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt="0.3"
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.18", features = ["serialize"] }
svd-rs = { git = "https://github.com/rust-embedded/svd", branch = "roxmltree", features = ["serde"]  }
svd-parser = { git = "https://github.com/rust-embedded/svd", branch = "roxmltree" }
svd-encoder = { git = "https://github.com/rust-embedded/svd", branch = "roxmltree" }
yaml-rust = "0.4"
anyhow = "1.0.43"
linked-hash-map = "0.5"
globset = "0.4.8"
commands = "0.0.5"

[dev-dependencies]
tempfile = "3.1"
